aikido/STYLE.md

**[IN PROGRESS]**
This PR improves the style guide documentation via simple example code and notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/75)

Update STYLE.md in aikido

---

aikido/include/aikido/statespace/CartesianProduct.hpp
aikido/include/aikido/statespace/Rn.hpp
aikido/include/aikido/statespace/SE2.hpp
aikido/include/aikido/statespace/SE3.hpp
aikido/include/aikido/statespace/SO2.hpp
aikido/include/aikido/statespace/SO3.hpp
aikido/include/aikido/statespace/StateSpace.hpp
aikido/src/statespace/CartesianProduct.cpp
aikido/src/statespace/Rn.cpp
aikido/src/statespace/SE2.cpp
aikido/src/statespace/SE3.cpp
aikido/src/statespace/SO2.cpp
aikido/src/statespace/SO3.cpp
aikido/tests/statespace/test_CartesianProduct.cpp
aikido/tests/statespace/test_Rn.cpp
aikido/tests/statespace/test_SE2.cpp
aikido/tests/statespace/test_SE3.cpp
aikido/tests/statespace/test_SO2.cpp
aikido/tests/statespace/test_SO3.cpp

Suggestions for alternate formats for each StateSpace are welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/94)

Adding print functionality to aikido StateSpace

---

CMakeLists.txt
include/aikido/constraint/NonColliding.hpp
include/aikido/control/BarrettFingerPositionCommandExecutor.hpp
include/aikido/control/BarrettFingerSpreadCommandExecutor.hpp
include/aikido/control/BarrettHandPositionCommandExecutor.hpp
include/aikido/statespace/dart/SO2Joint.hpp
src/constraint/TSR.cpp
src/control/BarrettFingerPositionCommandExecutor.cpp
src/control/BarrettFingerSpreadCommandExecutor.cpp
src/statespace/dart/MetaSkeletonStateSpace.cpp
src/statespace/dart/SO2Joint.cpp
tests/constraint/test_DifferentiableIntersection.cpp
tests/constraint/test_FramePairDifferentiable.cpp
tests/constraint/test_NonColliding.cpp
tests/constraint/test_RnBoxConstraint.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/113)

Support DART 6.1

---

CMakeLists.txt
cmake/uninstall_target.cmake.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/127)

Add uninstall target

---

src/rviz/ShapeFrameMarker.cpp
src/rviz/shape_conversions.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/131)

Suppress warnings due to using deprecated API of DART

---

include/aikido/constraint/NonColliding.hpp
include/aikido/constraint/TestableIntersection.hpp

Added for convenience. Should we maybe do this for all classes in constraint?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/137)

Adds NonCollidingPtr and TestableIntersectionPtr.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/140)

Add installation instruction on macOS using Homebrew

---

README.md
STYLE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/144)

Add instruction for auto formatting

---

README.md

Add missing $ to README.md

---

src/perception/AprilTagsModule.cpp
src/rviz/FrameMarker.cpp
src/rviz/ShapeFrameMarker.cpp

changed the frame used by rviz and took out  the unneeded print statements in perception

changed frame for HERB3

---

src/perception/AprilTagsModule.cpp
src/rviz/FrameMarker.cpp
src/rviz/ShapeFrameMarker.cpp

Reverts personalrobotics/aikido#177

Revert "changed frame for HERB3"

---

CMakeLists.txt
cmake/Findactionlib.cmake
cmake/Findinteractive_markers.cmake
cmake/Findpr_control_msgs.cmake
cmake/Findtf.cmake
src/perception/CMakeLists.txt
src/rviz/CMakeLists.txt

as suggested by @psigen in #197

Use custom CMake modules for interactive_markers and tf

---

include/aikido/rviz/ResourceServer.hpp
src/rviz/ResourceServer.cpp

Fix inconsistent function signature

---

include/aikido/util/PseudoInverse.hpp
include/aikido/util/VanDerCorput.hpp
src/util/VanDerCorput.cpp
tests/util/test_VanDerCorput.cpp

Add VanDerCorput::getLength()

---

CHANGELOG.md
CMakeLists.txt
package.xml

Next time, let's update the changelog per PR. :sob:

Packaging 0.1.0

---

include/aikido/constraint/NonColliding.hpp
src/constraint/NonColliding.cpp

Remove redundant constructor of NonColliding

---

README.md

Feel free to correct any unclear statement or errors.
***

Update install instruction in README.md

---

README.md

Add missing dependent PPAs of PRL's PPA

---

README.md

Use add-apt-repository instead of apt-add-repository

---

.travis.yml

Cache Homebrew to speed up build on macOS

---

.ci/before_install_linux.sh
.ci/install_linux.sh
.ci/install_macos.sh
.ci/script_linux.sh
.ci/script_macos.sh

Add set -ev to all .ci scripts.

---

CHANGELOG.md
src/io/CMakeLists.txt

Fix typo in #290

---

CHANGELOG.md
LICENSE

* Update release date of AIKIDO 0.2.0 in CHANGELOG.md
* Add #265 to CHANGELOG.md (resolves #283)
* Update copyright

Packaging AIKIDO 0.2.0

---

CMakeLists.txt

Add docs_forced to regenerate Doxygen documentation

---

src/planner/vectorfield/CMakeLists.txt

Add missing planner dependency to planner_vectorfield

---

include/aikido/common/StepSequence.hpp
src/common/StepSequence.cpp
tests/common/test_StepSequence.cpp

**Summary**
* Update docstring
* Allow taking negative steps
* Computes length only once

Improvements for #320

---

README.md

[Codacy](https://app.codacy.com) is an automated code reviews and code analytics service. [Here](https://app.codacy.com/app/jslee02/aikido/dashboard) is the dashboard for AIKIDO.
Codacy has several static analysis tools where two of them (cppcheck and shellcheck) are applicable to AIKIDO.
I found two other alternatives to Codacy, but they don't fit AIKIDO because:
* [Codebeat](https://codebeat.co/) doesn't support C++ projects
* [Code Climate](https://codeclimate.com/) isn't free for open source projects

Setup online static code analyzer: Codacy

---

CHANGELOG.md

@sniyaz forgot to mention this!

Update changelog for #324

---

include/aikido/distance/SE2Weighted.hpp
include/aikido/planner/World.hpp
tests/control/test_BarrettHandKinematicSimulationPositionCommandExecutor.cpp
tests/planner/ompl/OMPLTestHelpers.hpp
tools/check_format.sh

Minor code style issues raised at Codacy, namely:
1. `explicit` class constructor if taking a single argument.
2. Pass by reference when relevant.
***
Following aren't really applicable. 

Fix code style

---

include/aikido/control/KinematicSimulationTrajectoryExecutor.hpp
include/aikido/statespace/StateSpace.hpp
include/aikido/statespace/dart/MetaSkeletonStateSpace.hpp
include/aikido/trajectory/Interpolated.hpp
include/aikido/trajectory/Spline.hpp
include/aikido/trajectory/Trajectory.hpp
src/control/InstantaneousTrajectoryExecutor.cpp
src/control/KinematicSimulationTrajectoryExecutor.cpp
src/control/ros/Conversions.cpp
src/control/ros/RosTrajectoryExecutor.cpp
src/planner/parabolic/ParabolicTimer.cpp
src/planner/parabolic/ParabolicUtil.cpp
src/planner/parabolic/ParabolicUtil.hpp
src/rviz/TrajectoryMarker.cpp
src/statespace/StateSpace.cpp
src/statespace/dart/MetaSkeletonStateSpace.cpp
src/trajectory/Interpolated.cpp
src/trajectory/Spline.cpp

This PR addresses Issue #281 
***
Most of the following do not apply.

const stateSpace (and interpolator) for Trajectories

---

package.xml

Update AIKIDO maintainers.

---

.ci/install_macos.sh
.ci/script_macos.sh
.travis.yml
Brewfile
README.md

Enable macOS builds on Travis CI

---

src/robot/util.cpp

This was introduced in #426, and I merged the PR impatiently. :sweat: 
***

Fix compilation error in robot/util.cpp

---

CHANGELOG.md
src/rviz/InteractiveMarkerViewer.cpp
src/rviz/WorldInteractiveMarkerViewer.cpp

This change is from `herb2_ws`, I think while we were trying to diagnose the skeleton locking issue. I'm not entirely sure whether it's necessary, but I don't think it'd hurt?
***

Join Viewer threads on setAutoUpdate(false).

---

CHANGELOG.md
include/aikido/constraint/uniform/SE2BoxConstraint.hpp
include/aikido/distance/SE2Weighted.hpp
include/aikido/statespace/SE2.hpp
src/constraint/uniform/SE2BoxConstraint.cpp
src/distance/SE2.cpp
src/distance/SE2Weighted.cpp
src/statespace/SE2.cpp
src/statespace/dart/SE2Joint.cpp
tests/constraint/SampleGeneratorCoverage.hpp
tests/constraint/test_SE2BoxConstraint.cpp
tests/distance/test_SE2Weighted.cpp
tests/statespace/test_SE2.cpp

Follow DART SE(2) convention

---

src/distance/ConfigurationRanker.cpp
tests/distance/test_NominalConfigurationRanker.cpp

Travis is failing because of `clang-format` issues.

Fix formatting.

---

.ci/after_failure.sh
.ci/script_linux.sh
cmake/CodeCoverage.cmake

Upload to CodeCov from CodeCoverage.cmake

---

CMakeLists.txt

Resolves https://github.com/personalrobotics/aikido/issues/488
***

Warn for skipped modules

---

CHANGELOG.md
include/aikido/planner/vectorfield/VectorFieldPlanner.hpp
src/planner/vectorfield/VectorFieldPlanner.cpp
src/planner/vectorfield/detail/VectorFieldIntegrator.cpp
src/planner/vectorfield/detail/VectorFieldIntegrator.hpp
tests/planner/vectorfield/test_VectorFieldPlanner.cpp

Return Interpolated from VectorFieldPlanner.

---

src/distance/CMakeLists.txt

Added SE2.hpp to distance CMakeLists.txt
***

Added SE2.hpp to distance CMakeLists.txt

---

include/aikido/constraint/uniform/detail/RnConstantSampler-impl.hpp
src/constraint/dart/InverseKinematicsSampleable.cpp
src/constraint/dart/TSR.cpp

Remove dtwarn redefinitions.

---

.travis.yml

By recommendation of @jslee02. This should unblock https://github.com/personalrobotics/aikido/pull/579.
***

Bump OSX Travis image version to fix crash.

---

src/rviz/shape_conversions.cpp

[Describe this pull request. Link to relevant GitHub issues, if any.]
Adding convertShape for SphereShape under rviz/shape_conversion.cpp.
[Explain how this pull request was tested.]
***

Adding conversion from SphereShape to ROS msg

---

CHANGELOG.md
include/aikido/rviz/FrameMarker.hpp
include/aikido/rviz/InteractiveMarkerViewer.hpp
include/aikido/rviz/TSRMarker.hpp
src/rviz/FrameMarker.cpp
src/rviz/InteractiveMarkerViewer.cpp
src/rviz/TSRMarker.cpp

See #617 for more details on the issue and proposed fix
This code was tested by ensuring that ada_feeding's "Check TSR" code (e.g., [here](actions where they ask the researcher to check the TSR)) does not crash.
***
- [N/A] Document new methods and classes
- [N/A] Add unit test(s) for this change

Fix the AddTSRMarker Bug

---

CHANGELOG.md
include/aikido/rviz/InteractiveMarkerViewer.hpp
src/rviz/InteractiveMarkerViewer.cpp

Add ability to clear frame and trajectory markers from Rviz
