- aikido/include/aikido/constraint/CyclicSampleable.hpp
- aikido/include/aikido/constraint/NonColliding.hpp
- aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp
- aikido/include/aikido/planner/ompl/Planner.hpp
- aikido/include/aikido/planner/ompl/dart.hpp
- aikido/include/aikido/planner/ompl/detail/Planner-impl.hpp
- aikido/src/constraint/NonColliding.cpp
- aikido/src/planner/ompl/GeometricStateSpace.cpp
- aikido/src/planner/ompl/GoalRegion.cpp
- aikido/src/planner/ompl/Planner.cpp
- aikido/src/planner/ompl/StateSampler.cpp
- aikido/src/planner/ompl/StateValidityChecker.cpp
- aikido/src/planner/ompl/dart.cpp
- aikido/src/planner/parabolic/ParabolicTimer.cpp
- aikido/tests/planner/ompl/test_GeometricStateSpace.cpp
- aikido/tests/planner/ompl/test_GoalRegion.cpp
- aikido/tests/planner/ompl/test_MotionValidator.cpp
- aikido/tests/planner/ompl/test_OMPLPlanner.cpp
- aikido/tests/planner/ompl/test_StateSampler.cpp
- aikido/tests/planner/ompl/test_ValidityChecker.cpp
This PR contains a set of improvements/bug fixes that were necessary to use the aikido framework and OMPL planners with HERB:
* Aikido state now set to a nullptr when a valid sample fails to be generated.  This includes regular state and goal sampling
* GeometricStateSpace, StateSampler, StateValidityChecker and GoalRegion updated to properly handle these states.
* Additional logic to ```aikido::constraint::NonColliding``` to pass collision options that ignore collisions between physically adjacent links by default.  Also added a constructor that exposes the option of passing custom ```CollisionOptions``` to the constraint.
* Added checks for infinite velocity or acceleration limits to ```ParabolicTimer```
* Update OMPL planner functions to use the custom ```MotionValidator``` by default …
> Improvements needed for planning with OMPL for HERB

- CMakeLists.txt
Some IDEs including Qt Creator doesn't show the headers when they are not in a build target. This PR adds a dummy custom target that contains the headers for displaying them in IDEs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/121)
> Add custom target for displaying the headers in IDEs

- CMakeLists.txt
- cmake/aikidoConfig.cmake.in
This PR allows us to check the Aikido version when we find the package. E.g.,
```cmake
find_package(aikido 0.0.1 REQUIRED COMPONENTS  # This project requires Aikido 0.0.1 or greater.
constraint
distance
planner_ompl
planner_parabolic
statespace
util)
```
Also, we could use the version variable in CMake script as
```cmake
message(STATUS "Found Aikido ${aikido_VERSION}$") # will be printed as: Found Aikido 0.0.1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/124)
> Setup versioning for CMake

- src/planner/ompl/MotionValidator.cpp
This compilation error wasn't caught by Travis CI, so I suspect a silent exclusion of the planner_ompl module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/133)
> fix missing argument to VanDerCorput constructor

- src/util/VanDerCorput.cpp
This PR includes the missing headers `<algorithm>` and `<stdexcept>` to `VanDerCorput.cpp` for `std::max()` and `std::out_of_range`, respectively.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/138)
> Add missing STL headers

- include/aikido/constraint/InverseKinematicsSampleable.hpp
- include/aikido/planner/ompl/CRRT.hpp
Searched them using regexp: `^ *virtual .*override`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/141)
> Remove redundant virtual keyword for overriding member functions

- CMakeLists.txt
- include/aikido/planner/ompl/BackwardCompatibility.hpp
- include/aikido/planner/ompl/CRRT.hpp
- include/aikido/planner/ompl/Planner.hpp
- include/aikido/planner/ompl/detail/Planner-impl.hpp
- package.xml
- src/planner/ompl/CRRT.cpp
- src/planner/ompl/CRRTConnect.cpp
- src/planner/ompl/GeometricStateSpace.cpp
- src/planner/ompl/Planner.cpp
Tested for:
* macOS 10.12 + OMPL 1.3 (STL smart pointers)
* Ubuntu 14.04 LTS + OMPL 0.13 (boost smart pointers)
* Ubuntu 14.04 LTS + OMPL 1.0.0 (boost smart pointers)
Related issue: #132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/139)
> Support for OMPL 1.2.0 and above

- include/aikido/rviz/InteractiveMarkerViewer.hpp
- include/aikido/rviz/SmartPointers.hpp
- include/aikido/rviz/TSRMarker.hpp
- src/rviz/CMakeLists.txt
- src/rviz/InteractiveMarkerViewer.cpp
- src/rviz/TSRMarker.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/personalrobotics/aikido/136)
> Addes TSR visualizer to aikido/rviz.

- tests/control/test_KinematicSimulationTrajectoryExecutor.cpp
`KinematicSimulationTrajectoryExecutorTest.execute_TrajectoryIsAlreadyRunning_Throws` test occasionally fails because the result is non-deterministic. This PR fixes the test to take into account the case as well.
Resolves #126
> Fix test_KinematicSimulationTrajectoryExecutor

- package.xml
[`yaml-cpp` was added to CMake script as an optional dependency](https://github.com/personalrobotics/aikido/blob/master/src/perception/CMakeLists.txt#L4-L5). This PR adds `yaml-cpp` to `package.xml` as required dependency because `package.xml` doesn't support adding an optional dependency.
Resolves #134
> Add yaml-cpp to package.xml as dependency

- include/aikido/control/BarrettHandKinematicSimulationPositionCommandExecutor.hpp
- include/aikido/control/KinematicSimulationTrajectoryExecutor.hpp
- include/aikido/trajectory/Trajectory.hpp
- src/control/KinematicSimulationTrajectoryExecutor.cpp
`KinematicSimulationTrajectoryExecutor::step()` should no longer lock the skeleton and let the caller be responsible for locking if it's running under multi-threaded setting. This is consistent with other executors.
> Removes locking from step()

- include/aikido/control/ros/RosPositionCommandExecutor.hpp
- include/aikido/control/ros/RosTrajectoryExecutor.hpp
- src/control/ros/CMakeLists.txt
- src/control/ros/RosTrajectoryExecutor.cpp
This PR renames `spin` to `step` so that the method properly overrides `TrajectoryExecutor::step`. It also removes templating of `connectionTimeout` and `connectionPollingPeriod` in the constructor.
> Bugfix: renaming spin to step and removing template from RosTrajectoryExecutor

- include/aikido/control/ros/RosTrajectoryExecutor.hpp
- src/control/ros/RosTrajectoryExecutor.cpp
This replaces the specific `waitForServer()` function in `control/ros/RosTrajectoryExecutor` with a call to the util function `waitForActionServer` introduced in #173 
It also addresses the bug that the earlier `waitForServer()` function had, which was that it initialized `currentTime` with an extra `timeoutDuration`
> Using helper function for waiting for action server

- src/planner/SnapPlanner.cpp
- tests/planner/test_SnapPlanner.cpp
SnapPlanner's docstring says that it returns `nullptr` when it fails but the implementation returned trajectory.  This PR fixes it to return `nullptr` upon failure.
> Changes SnapPlanner to return nullptr when planning fails.

- CMakeLists.txt
- src/rviz/shape_conversions.cpp
- tests/constraint/test_DifferentiableIntersection.cpp
- tests/constraint/test_FramePairDifferentiable.cpp
This PR increases the minimum required DART version to 6.2.0, which is just released today and available installing through the PPA. Also, this PR suppresses warnings due to the use of deprecated API in DART 6.2.0.
> Increase minimum required DART version to 6.2.0

- include/aikido/util/RNG.hpp
- src/constraint/JointStateSpaceHelpers.cpp
- src/util/RNG.cpp
Resolves #187.
@mkoval is this what you meant? My initial thought was to have the two methods:
- `splitEngine(RNG& _engine, size_t _numOutputs, size_t _numSeeds = NUM_DEFAULT_SEEDS)` (already exists)
- `splitEngine(RNG& _engine, size_t _numSeeds = NUM_DEFAULT_SEEDS)` (call the former with `_numOutputs = 1`)
but this makes `splitEngine(RNG&, size_t)` ambiguous.
> Set default `_numOutputs` to 1 in `splitEngine`

- include/aikido/control/ros/RosTrajectoryExecutor.hpp
- src/control/ros/RosJointStateClient.cpp
Issues:
It seems that `RosTrajectoryExecutor::transitionCallback` is sometimes not being called at all. On other trajectories, it _is_ being called and `isSuccessful` is true (the resulting message is `"Execution failed"`, which seems like a [typo](https://github.com/personalrobotics/aikido/blob/427f7be13b5b65a87316a2e7c7109dd8a0b07a37/src/control/ros/RosTrajectoryExecutor.cpp#L178)?) and the promise's value seems to be set. In both cases, the future still doesn't seem to be fulfilled. I thought that calling `future::wait` would return once a value is set by `promise::set_value`, but I could be misunderstanding.
When `RosTrajectoryExecutor::transitionCallback` is being called, it also seems that it is called with `handle.getCommState() == DONE` well before the trajectory actually …
> Fixes to work on real hardware

- include/aikido/statespace/dart/MetaSkeletonStateSpaceSaver.hpp
- include/aikido/statespace/dart/detail/MetaSkeletonStateSpaceSaver-impl.hpp
resolving personalrobotics/aikido #218
> save joint limits of space in MetaSkeletonStateSpaceSaver

- include/aikido/rviz/ResourceServer.hpp
- src/rviz/ResourceServer.cpp
Resolves #233. I don't know why this passed through Travis.
***
> Fix ResourceServer::resourceReaderCallback types.

- include/aikido/statespace/dart/detail/MetaSkeletonStateSpaceSaver-impl.hpp
Remove compile warning in `MetaSkeletonStateSaver`, which is introduced in adding new functions.
#185 
***
> remove compile warning

- CHANGELOG.md
- include/aikido/planner.hpp
- include/aikido/planner/World.hpp
- src/planner/CMakeLists.txt
- src/planner/World.cpp
- tests/planner/CMakeLists.txt
- tests/planner/test_World.cpp
This is a first attempt at a kinematic version of `dart::simulation::World`. Using a DART `World` as our default environment representation forces users to instantiate a dynamics engine, which is unnecessary overhead for many of our tasks. We'll add more functionality in future PRs.
***
> Initial implementation of kinematic World

- CHANGELOG.md
- include/aikido/perception/AprilTagsModule.hpp
- include/aikido/perception/PerceptionModule.hpp
- include/aikido/rviz.hpp
- include/aikido/rviz/InteractiveMarkerViewer.hpp
- include/aikido/rviz/WorldInteractiveMarkerViewer.hpp
- src/perception/AprilTagsModule.cpp
- src/rviz/CMakeLists.txt
- src/rviz/FrameMarker.cpp
- src/rviz/WorldInteractiveMarkerViewer.cpp
This subclasses `aikido::rviz::InteractiveMarkerViewer` to create a viewer for a `dart::simulation::World`. This would automatically update the viewer as skeletons are added to the `World`, which is a first step toward using them properly in all of our demo scripts.
@psigen mentioned that `dart::simulation::World` has some additional overhead if we aren't doing things with dynamics. I'm using `World` for now for lack of something better in DART, but we should seriously think about a better longer-term solution.
Other issues:
***
> Add WorldInteractiveMarkerViewer.

- CHANGELOG.md
- include/aikido/constraint/NonColliding.hpp
- src/constraint/NonColliding.cpp
- tests/constraint/test_NonColliding.cpp
> Add methods for removing groups in NonColliding.

- CHANGELOG.md
- src/CMakeLists.txt
- src/rviz/CMakeLists.txt
I was having trouble compiling dart_examples while working on https://github.com/personalrobotics/dart_examples/pull/8. This seemed to fix it.
- `constraint` is used because we visualize TSRs
- `planner` is used because we visualize `World`s
***
> Add rviz dependencies.

- .travis.yml
Currently, Travis CI tests on macOS almost always timeout. This PR disables it as we don't have any actual use AIKIDO on macOS.
***
> Disable CI tests on macOS

- CHANGELOG.md
- include/aikido/planner/World.hpp
- include/aikido/rviz/WorldInteractiveMarkerViewer.hpp
- src/planner/World.cpp
- src/rviz/WorldInteractiveMarkerViewer.cpp
If a `Skeleton` is removed and a new `Skeleton` with the same name is added quickly enough (before the viewer refreshes and removes the original `Skeleton`), the new `Skeleton` is not visualized. This PR fixes this bug by using the actual `SkeletonPtr` as the key in `WorldInteractiveMarkerViewer`, rather than its name.
At some point, we could fix this by registering callbacks to `World` that are called when adding or removing `Skeleton`s.
***
> Fix WorldInteractiveMarkerViewer bug when removing Skeletons

- .ci/install_linux.sh
Resolves #227.
The issue was that `cp "${TRAVIS_BUILD_DIR}" src` doesn't copy the source directory (missing `-r`), so the next line ` ./scripts/internal-distro.py --workspace=src distribution.yml --repository "${REPOSITORY}"` will clone the repository into the workspace. The cloned repository will be on the default branch.
***
> Fix Travis builds

- CHANGELOG.md
- include/aikido/statespace/dart/MetaSkeletonStateSpaceSaver.hpp
- src/statespace/CMakeLists.txt
- src/statespace/dart/MetaSkeletonStateSpaceSaver.cpp
- tests/statespace/CMakeLists.txt
- tests/statespace/dart/test_MetaSkeletonStateSpaceSaver.cpp
This PR moves `MetaSkeletonStateSpaceSaver`'s implementation from a header file to a cpp file. The current version results in multiple definition error when two classes import `MetaSkeletonStateSpaceSaver`.
***
> Move MetaSkeletonStateSpaceSaver implementation to a cpp file.

- .ci/before_install_linux.sh
- .ci/install_linux.sh
- .ci/install_macos.sh
- .ci/script_linux.sh
- .ci/script_macos.sh
The shebang `#!/usr/bin/env bash -e` works on my Mac but not on my Ubuntu workstation (I see `/usr/bin/env: bash -e: No such file or directory` instead). This PR uses `set -e` instead.
***
> Update shebangs and shellopts for CI scripts.

- STYLE.md
I think we've been struggling from whether we should pass a `std::shared_ptr` by value or by const reference. I found a reliable article about this and think it would be good to add this to our guideline.
This isn't a complete guideline about `shared_ptr`, but it would be worth to start to have.
> Add guidelines for use of smart pointers

- .travis.yml
Travis CI recently added `group` field to specify which image to be used. `group: travis_lts` (default) is a stable image while `group: travis_latest` is an image that is frequently being updated with new packages.
I believe we want to use `group: travis_latest`.
Related links:
* https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
* https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images
> Add group field to .travis.yml

- CHANGELOG.md
- cmake/FindTinyXML2.cmake
- src/io/CMakeLists.txt
- src/io/CatkinResourceRetriever.cpp
There were API breaking changes in tinyxml2 6.0.0. This PR adds band-aid to support tinyxml2 6.0.0 and less.
Referenced https://bitbucket.org/ignitionrobotics/ign-common/pull-requests/87/support-new-errorstr-api-in-tinyxml2-600/diff
***
> Support new ErrorStr API in tinyxml2 6.0.0

- CHANGELOG.md
- include/aikido/rviz/InteractiveMarkerViewer.hpp
- include/aikido/rviz/SmartPointers.hpp
- include/aikido/rviz/TrajectoryMarker.hpp
- include/aikido/rviz/shape_conversions.hpp
- src/planner/vectorfield/detail/VectorFieldIntegrator.cpp
- src/rviz/CMakeLists.txt
- src/rviz/InteractiveMarkerViewer.cpp
- src/rviz/TrajectoryMarker.cpp
- src/rviz/WorldInteractiveMarkerViewer.cpp
- src/rviz/shape_conversions.cpp
This PR adds `aikido::rviz::TrajectoryMarker` for visualizing trajectories in RViz.
The inputs are:
* `aikido::trajectory::Trajectory`: A C-space trajectory used to compute task-space trajectory
* `dart::dynamics::Skeleton`: Target skeleton the trajectory is applied to.
* `dart::dynamics::Frame`: Target frame to visualize the trajectory of the origin.
`aikido::rviz::TrajectoryMarker` has several rendering options:
* trajectory color (RBGA)
* trajectory thickness
* number of line-segments of the task-space trajectory
Example:
***
> Add TrajectoryMarker

- include/aikido/control/BarrettFingerKinematicSimulationPositionCommandExecutor.hpp
- include/aikido/control/BarrettFingerKinematicSimulationSpreadCommandExecutor.hpp
- src/control/BarrettFingerKinematicSimulationPositionCommandExecutor.cpp
- src/control/BarrettFingerKinematicSimulationSpreadCommandExecutor.cpp
- src/control/BarrettHandKinematicSimulationPositionCommandExecutor.cpp
- tests/control/test_BarrettHandKinematicSimulationPositionCommandExecutor.cpp
`BarrettHandKinematicSimulationPositionCommandExecutor::setCollideWith` didn't call `setCollideWith` on the underlying position or spread executors. In addition, calling `BarrettFingerKinematicSimulationPositionCommandExecutor::setCollideWith` and `BarrettFingerKinematicSimulationSpreadCommandExecutor::setCollideWith` could result in a mismatch if the new `CollisionGroup` came from a different `CollisionDetector`.
This PR fixes the first issue and adds a `setFingerCollisionGroup` method to both finger executors, which updates the appropriate finger collision groups (if necessary).
I think this resolves #271. (I didn't see the `setCollideWith` methods when I created the issue earlier.)
***
> Fix CollisionGroup bugs in Hand executors.

- CHANGELOG.md
- src/common/StepSequence.cpp
- tests/common/test_StepSequence.cpp
In current `aikido`, unexpected exception is thrown in some cases.
`StepSequence seq(0.2, false); for (double v : seq) { DART_UNUSED(v); count++; }`
An exception will be throw
>unknown file: Failure
>C++ exception with description "Indexed maximum intenger." thrown in the test body.
Expected sequence shall be `(0.0, 0.2, 0.4, 0.6, 0.8)`; but `getMaxSteps()` returns 6.
Thus an exception is triggered in `operator []`.
In this PR,
`StepSequence seq(0.2, true)` returns `(0.0, 0.2, 0.4, 0.6, 0.8, 1.0)` and `getMaxSteps()` returns 6.
`StepSequence seq(0.2, false)` returns `(0.0, 0.2, 0.4, 0.6, 0.8)` and `getMaxSteps()` returns 5.
Unit tests are updated accordingly.
> fix step sequence iterator

- CHANGELOG.md
- include/aikido/statespace/dart/JointStateSpace.hpp
- include/aikido/statespace/dart/MetaSkeletonStateSpace.hpp
- src/rviz/TrajectoryMarker.cpp
- src/statespace/dart/JointStateSpace.cpp
- src/statespace/dart/MetaSkeletonStateSpace.cpp
- tests/statespace/dart/test_DartJointStateSpaces.cpp
- tests/statespace/dart/test_MetaSkeletonStateSpace.cpp
> Add methods for checking compatibility between DART objects and statespaces

- src/planner/ompl/CMakeLists.txt
It seems that this `CMakeLists.txt` hasn't been updated since we introduced the `aikido_check_package` macro, so there was some redundancy here.
***
> Clean up planner_ompl CMakeLists.txt.

- .ci/before_install_linux.sh
- .ci/build_docs.sh
- .travis.yml
This is related to #68, although we should figure out how to deploy docs from tags before closing that issue.
***
> Configure Travis CI to automatically deploy docs from master

- STYLE.md
The major motivation of this PR is to make using `\tparam` for template argument as an explicit convention of AIKIDO, but it would be also worth to have guide for template classes.
> [WIP] Add style guide for template class

- include/aikido/common/pointers.hpp
This should help with #333 since we won't need DART's source code to generate the full macro expansion. In addition, we'll be generating more consistent documentation since DART defines shared/weak pointers with `typedef`, and we were defining unique pointers with `using`.
***
> Stop using DART's smart pointer macro.

- CHANGELOG.md
- include/aikido/planner/WorldStateSaver.hpp
- include/aikido/statespace/dart/MetaSkeletonStateSaver.hpp
- src/planner/WorldStateSaver.cpp
- src/planner/vectorfield/VectorFieldPlanner.cpp
- src/rviz/TrajectoryMarker.cpp
- src/statespace/dart/MetaSkeletonStateSaver.cpp
- tests/statespace/dart/test_MetaSkeletonStateSaver.cpp
Resolves #276. Resolves #293.
This implementation might not be ideal because the "options" can be arbitrary ints, rather than combinations of the options that we actually enumerate. If that's a problem, maybe something like [this](http://blog.bitwigglers.org/using-enum-classes-as-type-safe-bitmasks/) would be better?
***
> Add flags to Saver classes to specify what to save

- .travis.yml
Based on the following references, this PR disables deploy for Travis CI's cron builds. But, I'm not sure if the syntax is correct though. Here is the instruction for `condition`:
> condition: deploy when a single bash condition evaluates to true. This must be a string value, and is equivalant to if [[ <condition> ]]; then <deploy>; fi. For example, $CC = gcc.
Another possible expression would be:
```shell
condition: "$BUILD_TYPE -eq Release -a  $TRAVIS_EVENT_TYPE -ne cron"
```
References:
* https://docs.travis-ci.com/user/deployment
* https://docs.travis-ci.com/user/environment-variables/
* https://stackoverflow.com/questions/3826425/how-to-represent-multiple-conditions-in-a-shell-if-statement
> Skip deploy for cron build

- cmake/Doxyfile.in
Resolves #333. Turns off verbose Doxygen output so warnings are actually noticeable.
***
> Fix smart pointer documentation.

- src/common/StepSequence.cpp
- src/control/KinematicSimulationTrajectoryExecutor.cpp
- tests/control/test_InstantaneousTrajectoryExecutor.cpp
- Remove unnecessary `std::move` introduced by #337 
- Remove unused `precision` from `StepSequence`, as suggested in #220 
- Remove unused `stepTime` from `test_InstantaneousTrajectoryExecutor`
***
> Fix clang warnings

- CMakeLists.txt
The external link to DART in Doxygen's tree view (left navigation) is generated incorrectly. When on a page that is not at the top level of `aikido/master` (e.g. [this](https://personalrobotics.github.io/aikido/master/d0/d16/md_include_aikido_statespace_README.html)), the resulting link points to `https://personalrobotics.github.io/aikido/master/http://dartsim.github.io/dart/v6.3.0/index.html` rather than `http://dartsim.github.io/dart/v6.3.0/index.html`.
The Doxygen-generated JavaScript that generates the side navigation [`navtree.js`](https://github.com/doxygen/doxygen/blob/dc11a3f6a207b3539ffe55a20164d4a90961ff30/templates/html/navtree.js#L209) suggests that if the first character of the link is `^`, then the remainder of the link will be taken (rather than blindly adding a relative …
> Add missing ^ in generated navtree.js for external links.

- src/planner/ompl/CMakeLists.txt
This is a temporary solution for the [test failures](https://github.com/personalrobotics/aikido/issues/363) with OMPL (>= 1.2.0) + GCC.
***
> Disable OMPL planners for OMPL (>= 1.2.0) + GCC

- src/planner/ompl/CMakeLists.txt
This PR uses `ompl` instead of `OMPL` to find OMPL. This is because [OMPL changed the config file name from `ompl-config.cmake` to `omplConfig.cmake`](https://bitbucket.org/ompl/ompl/commits/a4612f15d931721e44de015df7b1bd5129836850) in version 1.3.2. CMake supports two patters for config names: X-config.cmake and XConfig.cmake (where X is the package name). The former pattern is not case sensitive so that we could find the package using either `x` or `X`, but the later pattern is case sensitive. That said, we should use `ompl` to be able to work over the two patterns. 
***
> Use "ompl" to find OMPL package

- include/aikido/control/TrajectoryExecutor.hpp
- src/control/InstantaneousTrajectoryExecutor.cpp
- src/control/KinematicSimulationTrajectoryExecutor.cpp
This was introduced by #349.
***
> Allow KinematicSimulationTrajectoryExecutor to execute trajectories containing subsets of the skeleton.

- CHANGELOG.md
- package.xml
Depends on https://github.com/personalrobotics/pr-cleanroom/pull/14.
In the CI scripts, we should now run something like
```
./scripts/internal-distro.py ... -o OPTIONAL
```
where `OPTIONAL` is the name of the dependency group below.
***
> Mark optional dependencies in package.xml.

- package.xml
[The ROS package name of DART was changed to `dartsim`](https://github.com/dartsim/dart/pull/1027).
This PR depends on https://github.com/personalrobotics/pr-rosinstalls/pull/38.
***
> Update package name of DART

- CHANGELOG.md
- include/aikido/io/util.hpp
- src/io/util.cpp
- tests/io/CMakeLists.txt
- tests/io/test_loadSkeletonFromURDF.cpp
- tests/resources/urdf/objects/block.urdf
- tests/resources/urdf/objects/ground.urdf
- Changed API to take in a DART `Uri` rather than string. (Strings can be automatically converted to `Uri`s.)
- Only try to convert to a `FreeJoint` if a transform has been provided. (We might want to load `Skeleton`s with fixed joints, but wouldn't set a transform in this case.)
***
> Minor changes to aikido::io::loadSkeletonFromURDF.

- include/aikido/control/TrajectoryExecutor.hpp
`traj` was documented as `_traj`. Continuation of #357.
***
> Fix documentation typo.

- .ci/before_install_linux.sh
- .ci/script_linux.sh
I think we're unnecessarily defining `PACKAGE_NAMES` in `before_install_linux.sh`. As far as I can tell, we only use it in `script_linux.sh`.
> [ci] Define variables where they're used.

- .travis.yml
The Travis GitHub Pages deployment requires that paths are specified as relative paths and doesn't support absolute paths. This PR makes the previously-specified relative path resolve to the correct directory.
> Add before_deploy step to .travis.yml.

- tests/constraint/test_SE2BoxConstraint.cpp
- tests/planner/parabolic/test_ParabolicSmoother.cpp
- tests/planner/parabolic/test_SmoothPostProcessor.cpp
This PR speeds up the tests that are taking an egregiously long time to run (40-120 seconds). The goal is to have every test under a second (hopefully, significantly under a second).
- One of the coverage tests in `test_SE2BoxConstraint` runs much faster in release mode than in debug mode. This PR reduces the number of points that are sampled in debug mode only.
- The default value for constraint-checking resolution (`1e-4`) in `ParabolicSmoother` might be too fine. We saw with one of the HERB demos that `1e-3` was sufficient for avoiding collisions without taking too long to run. Since our parabolic smoother tests are using the `Satisfied` constraint, there's no point in actually checking this at any resolution, so I set it to `1e-1` here.
Resolves #412.
***
**Before creating a pull …
> Speed up tests

- CHANGELOG.md
- include/aikido/planner/ConfigurationToEndEffectorOffset.hpp
- include/aikido/planner/ConfigurationToEndEffectorOffsetPlanner.hpp
- include/aikido/planner/vectorfield/VectorFieldConfigurationToEndEffectorOffsetPlanner.hpp
- include/aikido/planner/vectorfield/VectorFieldPlanner.hpp
- src/planner/CMakeLists.txt
- src/planner/ConfigurationToEndEffectorOffset.cpp
- src/planner/ConfigurationToEndEffectorOffsetPlanner.cpp
- src/planner/vectorfield/CMakeLists.txt
- src/planner/vectorfield/VectorFieldConfigurationToEndEffectorOffsetPlanner.cpp
- src/planner/vectorfield/VectorFieldPlanner.cpp
- src/robot/util.cpp
- tests/planner/vectorfield/test_VectorFieldPlanner.cpp
This PR has changes that use the new Planner API to refactor VFP.
Right now I've only refactored `planToEndEffectorOffset` by creating the new `VectorFieldConfigurationToEndEffectorOffsetPlanner` class. While these changes are looked over, I'll refactor `planToEndEffectorPose` as well.
**Summary of changes**
1) Create new `ConfigurationToEndEffectorOffsetPlanner` class for the `ConfigurationToEndEffectorOffset`  Problem.
2) Create `VectorFieldConfigurationToEndEffectorOffsetPlanner` class that extends the above and calls the old `planToEndEffectorOffset` method in `VectorFieldPlanner`.
**TODOs**
1) We need to figure out to handle the `startState` provided by `ConfigurationToEndEffectorOffset`. The old VFP code gets the current configuration from the metaSkeleton, so right now I just …
> Refactor VFP with new Planner API

- CHANGELOG.md
- src/control/KinematicSimulationTrajectoryExecutor.cpp
- tests/control/test_KinematicSimulationTrajectoryExecutor.cpp
- tests/control/test_QueuedTrajectoryExecutor.cpp
Other executors should fix this too, but I believe that they're now spread out across the different librobot repositories.
***
> Fix bug with negative execution times in Executor::step.

- CHANGELOG.md
- include/aikido/common/detail/Spline-impl.hpp
Resolves #451. I've tested this locally with both 3.3.4 and 3.3.5.
We should probably try to figure out how to take advantage of knowing the correct fixed-size output vector, but maybe this isn't possible.
***
> Fix compilation errors with Eigen 3.3.5

- src/planner/vectorfield/VectorFieldPlanner.cpp
This is only one line change so I did not create an issue.
In creating `MoveEndEffectorOffsetVectorField`, `mStartPose` is initialized from the current end-effector pose. https://github.com/personalrobotics/aikido/blob/master/src/planner/vectorfield/MoveEndEffectorOffsetVectorField.cpp#L32
We shall update the position of metaSkeleton before creating the vector field so that the start pose of the planning matches `mStartPose`. If not, it might start with a big deviation when the given `startState` is very different with current state of meta skeleton.
This is a fix to #426 
***
> Set start state to state space before creating vector field

- CHANGELOG.md
- src/planner/vectorfield/detail/VectorFieldIntegrator.cpp
- src/planner/vectorfield/detail/VectorFieldIntegrator.hpp
- tests/planner/vectorfield/test_VectorFieldPlanner.cpp
This PR fixes the last issue left in #365 
I have tested it on 32-bit machine. 
The previous code uses `createState()` of a state space to a `State` raw point, which causes problem in ownership and thus memory leak. 
The timilimit in the unit test is increased for successul rate.
***
> Fix segment fault on 32-bit machine

- CHANGELOG.md
- include/aikido/common/BSpline.hpp
- include/aikido/common/SplineFwd.hpp
- include/aikido/common/StepSequence.hpp
- include/aikido/trajectory/BSpline.hpp
- src/common/StepSequence.cpp
- src/trajectory/BSpline.cpp
- src/trajectory/CMakeLists.txt
- tests/trajectory/CMakeLists.txt
- tests/trajectory/test_BSpline.cpp
(This is a work-in-progress pull request to get early feedback.)
This PR adds `trajectory::BSpline`, implementation of B-spline trajectory, and necessary classes in `common` namespace.
Unlike `trajectory::Spline`, `trajectory::BSpline` guarantees class `C^k` continuity (`k - 1` times differentiable) over the whole trajectory where `k` is the order of B-spline.
`Eigen::Spline` (renamed to `aikido::common::BSpline`) and `Eigen::SplineTraits` are copied into AIKIDO code base with some modifications. The motivation of the adjustment is that Eigen's B-spline module doesn't allow changing control points after construction while we need this feature for trajectory optimization, which we will introduce soon.
Unit tests will be added before merging this PR.
*** …
> Add B-spline trajectory

- include/aikido/distance/ConfigurationRanker.hpp
- include/aikido/distance/JointAvoidanceConfigurationRanker.hpp
- include/aikido/distance/NominalConfigurationRanker.hpp
- src/distance/ConfigurationRanker.cpp
- src/distance/JointAvoidanceConfigurationRanker.cpp
- src/distance/NominalConfigurationRanker.cpp
- tests/distance/test_JointAvoidanceConfigurationRanker.cpp
- tests/distance/test_NominalConfigurationRanker.cpp
Allow to set weights for distance computation in configuration ranking
***
> Weighted configuration ranker

- include/aikido/statespace/CartesianProduct.hpp
- include/aikido/statespace/dart/CartesianProductMetaSkeletonStateSpace.hpp
- src/control/KinematicSimulationTrajectoryExecutor.cpp
- src/planner/kunzretimer/KunzRetimer.cpp
- src/statespace/CMakeLists.txt
- src/statespace/dart/CartesianProductMetaSkeletonStateSpace.cpp
- src/trajectory/util.cpp
- tests/trajectory/test_util.cpp
This PR adds `CartesianProductMetaSkeletonStateSpace` under dart space and modifies `KinematicSimulationTrajectoryExecutor` to take both `CartesianProductMetaSkeletonStateSpace` and `MetaSkeletonStateSpace`. This is necessary to execute R1 trajectories in simulation.
***
> Add CartesianProductMetaSkeletonStateSpace

- CHANGELOG.md
- cmake/CompilerSettings.cmake
This PR fixes the build issue in xenial + boost 1.58 + kinetic + dart 6.7.2 of
```
/usr/include/boost/math/constants/constants.hpp:277:3: error: unable to find numeric literal operator 'operator""Q'
```
It adds a compiler option.
***
> Enable -fext-numeric-literals on compiler

- cmake/CodeCoverage.cmake
#495 fixed the uploading process, but Codecov didn't know how to interpret the artifacts that were uploaded. Setting the project root directory with the `-R` flag allows the Codecov script to find the YAML configuration file, which will maybe finally fix everything...
> Fix Codecov uploads.

- .github/CODEOWNERS
Setting [code owners](https://help.github.com/articles/about-code-owners/) should help us automatically request reviewers.
> Define CODEOWNERS for AIKIDO components

- src/robot/util.cpp
Robot's util::planToTSR.cpp didn't actually match the API in the header, using non-const ranker.
***
> Fix const-ness in util's planToTSR

- CMakeLists.txt
- cmake/ClangFormat.cmake
- src/common/CMakeLists.txt
- src/constraint/CMakeLists.txt
- src/control/CMakeLists.txt
- src/control/ros/CMakeLists.txt
- src/distance/CMakeLists.txt
- src/io/CMakeLists.txt
- src/perception/CMakeLists.txt
- src/planner/CMakeLists.txt
- src/planner/kunzretimer/CMakeLists.txt
- src/planner/ompl/CMakeLists.txt
- src/planner/parabolic/CMakeLists.txt
- src/planner/vectorfield/CMakeLists.txt
- src/robot/CMakeLists.txt
- src/rviz/CMakeLists.txt
- src/statespace/CMakeLists.txt
- src/trajectory/CMakeLists.txt
- tests/CMakeLists.txt
- tests/constraint/CMakeLists.txt
- tests/planner/ompl/CMakeLists.txt
Solve issue #232 
Added CMake module for Clang Format based on the one from Chimera. Can specify requested clang-format version.
***
- [ n/a ] Document new methods and classes
- [ x ] Format code with `make format`
- [ n/a ] Set version target by selecting a milestone on the right side
- [ n/a ] Summarize this change in `CHANGELOG.md`
- [ n/a ] Add unit test(s) for this change
> Make code formatting script as a CMake module

- CHANGELOG.md
- src/trajectory/util.cpp
This PR fixes `toR1JointTrajectory(Interpolated)` to use `getWaypointTime()` when copying a waypoint to r1JointTrajectory.
***
> Fix toR1JointTrajectory(Intepolated)

- include/aikido/distance/NominalConfigurationRanker.hpp
- src/distance/NominalConfigurationRanker.cpp
- src/planner/dart/ConfigurationToConfiguration_to_ConfigurationToTSR.cpp
- src/robot/util.cpp
- tests/distance/test_NominalConfigurationRanker.cpp
This fixes the bug in NominalConfigurationRanker, which keeps a pointer to a state that may become cleared out.
I tested this in `ada_demos` and printed `mNominalConfiguration` in `evaluateConfiguration` to see that it matches the value passed to the constructor.
Resolves #515.
***
> Change NominalConfigurationRanker to store ScopedState

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- src/rviz/shape_conversions.cpp
This PR fixes `rviz::convertShape(MeshShape...)` method to use `getMeshPath` instead of `getMeshUri` for `meshUri`.
When a mesh is loaded via MeshShape, `convertShape(MeshShape...)` gets called. Since `meshUri` is used by Rviz, it has to be a raw filepath, which is not the case when using `getMeshUri`.
This was never an issue with Herb or Ada because we use `urdfLoader` and it constructs AssimpMesh, which doesn't call this function. It was discovered while @vinitha910  was trying to load cozmo mesh directly using raw filepaths. 
It has been tested by constructing cozmo with MeshShapes and visualizing it in Rviz through aikido InteractiveViewer.
***
> Fix convertShape to use getMeshPath

- CHANGELOG.md
- include/aikido/distance/SE2.hpp
- src/distance/SE2.cpp
Fix for [Issue #535](https://github.com/personalrobotics/aikido/issues/535)
Fix was tested in libcozmo's `StateSpace` class.
***
> fixed getStateSpace return type

- src/robot/util.cpp
@planc509 was having this compilation error, which may have been introduced in [#499](https://github.com/personalrobotics/aikido/pull/499/files#diff-aa512357e2a323b6efdea83791638706L442). I have the same issue on my Trusty machine.
@gilwoolee @jslee02 do you remember why this change was made? (We should be deprecating this function anyway, so maybe it doesn't matter...)
***
> Fix compilation error (maybe only on Trusty?)

- CMakeLists.txt
I noticed this because 
```
CMake Error at .../aikido/python/aikidopy/CMakeLists.txt:8 (execute_process):
Syntax error in cmake code at
.../aikido/python/aikidopy/CMakeLists.txt:9
when parsing string
from distutils.sysconfig import get_python_lib;\
print(get_python_lib(plat_specific=True, prefix=''))
syntax error, unexpected cal_SYMBOL, expecting $end (103)
```
It seems that these line breaks might not be supported by lower versions of CMake? So we might want to change that as well.
```
$ cmake --version
cmake version 2.8.12.2
```
***
> Only add python subdirectory if building aikidopy.

- CHANGELOG.md
- src/common/VanDerCorput.cpp
- tests/common/test_VanDerCorput.cpp
Expected behavior for VDC with resolution `0.5`:
1. If an edge is of length(span) 1, output is `0, 0.5, 1`.
2. If the edge is of length(span) 2, output is `0, 0.5, 1.0, 1.5, 2.0`.
Current behavior generates sequence for [0,1] and multiplies with length thus giving
1. `0, 0.5, 1.0`
2. `0, 1.0, 2.0`
We have been using Van der Corput sequence only for interpolated trajectories with [0, 1] time so it was not an issue.
This PR introduces a test that fails with the current master and proposes a fix.
***
> BugFix: Van der Corput - consider span for resolution check

- CHANGELOG.md
- src/rviz/InteractiveMarkerViewer.cpp
If the viewer has an underlying world, skeleton markers corresponding to skeletons in the world that have been removed continued to be visualized. When the world removes the skeleton, the `SkeletonPtr` is non-nullptr and therefore the control did not reach the line that erases the marker from the map. This PR reorganizes the code for correction.
Tested via `herb3_demos` scripts for addition, deletion and updates to skeletons.
@brianhou: As a side: I wonder if we should re-introduce the `WorldInteractiveMarkerViewer`, not in its previous state but just to reimplement the `updateSkeletonMarkers()` function to have fewer if conditions.  
***
> Bugfix in InteractiveMarkerViewer

- src/rviz/InteractiveMarkerViewer.cpp
#560 introduces a warning that breaks downstream Travis CI (including rewd_controllers)
***
- [ N/A ] Format code with `make format`
- [ N/A ] Set version target by selecting a milestone on the right side
- [ N/A ] Summarize this change in `CHANGELOG.md`
> Fixed warning introduced by 560

- src/control/ros/Conversions.cpp
- src/control/ros/RosJointStateClient.cpp
- src/control/ros/RosPositionCommandExecutor.cpp
- src/control/ros/RosTrajectoryExecutor.cpp
- src/perception/shape_conversions.cpp
- src/rviz/BodyNodeMarker.cpp
- src/rviz/FrameMarker.cpp
- src/rviz/InteractiveMarkerViewer.cpp
- src/rviz/ResourceServer.cpp
- src/rviz/ShapeFrameMarker.cpp
- src/rviz/shape_conversions.cpp
Somehow I see bunch of clang format changes so I'm creating a PR to address this. 
I'm on clang-format 6.0 so these seem to be correct? 
***
> Clang format

- CHANGELOG.md
- include/aikido/planner/ConfigurationToConfigurations.hpp
- src/planner/ConfigurationToConfigurations.cpp
See: https://github.com/personalrobotics/aikido/issues/445
I've gone through and checked that all planner problem classes hold only `ScopedState` instead of raw pointers (to prevent the dangling pointer issue mentioned above). 
It turns out the only class that needed fixing was `ConfigurationToConfigurations`. At some point, it looks like the other problems were moved over to holding `ScopedState`. This PR addresses this.
***
> Check that all planning problems only hold ScopedStates.

- src/planner/ompl/CMakeLists.txt
Replace `0` with `.`, as is done in the OMPL version check in the previous line.
This is required on newer version of CMake.
***
- [ N/A ] Format code with `make format`
- [ N/A ] Set version target by selecting a milestone on the right side
- [ N/A ] Summarize this change in `CHANGELOG.md`
> Change Boost version string to canonical representation

- CHANGELOG.md
- include/aikido/robot/ConcreteManipulator.hpp
- include/aikido/robot/ConcreteRobot.hpp
- include/aikido/robot/Robot.hpp
- src/robot/ConcreteManipulator.cpp
- src/robot/ConcreteRobot.cpp
Now that we've merged https://github.com/personalrobotics/aikido/pull/579 and all upstream PRs, it's time to delete the old PP functionality before we had these nice new methods. Specifically, we're throwing out `smoothPath`, `retimePath`, `retimePathWithKunz`, and the old version of `getTrajectoryPostProcessor` that was hardcoded to return a ParabolicSmoother.
This will break lots of things upstream, but we'll handle those separately.
***
> Delete old post-processor code.

- .travis.yml
For some reason OSX Travis is busted again, but bumping the image version (again) seems to fix things.
Hopefully unblocks https://github.com/personalrobotics/aikido/pull/574.
***
> Bump OSX Travis version to 12u.

- .travis.yml
OSX Travis is crashing again because of the same inability to find DART. Switching the image version again from 12u -> 12 seems to fix this.
***
> Fix crashing OSX Travis Image

- .github/CODEOWNERS
- .github/workflows/docs.yml
DOCS routine fails on 18.04 due to use of deprecated PyYAML version. This runs the workflow on 20.04 instead.
***
- [ N/A ] Format code with `make format`
> Update DOCS and CODEOWNERS

- .ci/build_docs.sh
- .ci/install_linux_cmake.sh
- .ci/script_catkin.sh
- .ci/script_cmake.sh
- .github/workflows/build-test.yml
- .github/workflows/docs.yml
- CMakeLists.txt
Our DOCS workflow hasn't actually been deployment to our environment since we migrated to Github Actions in #598
Adding this step should fix this. 
***
- [ N/A ] Format code with `make format`
- [ N/A, internal ] Summarize this change in `CHANGELOG.md`
> Add Docs deployment

- CHANGELOG.md
- include/aikido/robot/util.hpp
- include/aikido/statespace/dart/MetaSkeletonStateSpace.hpp
- src/control/KinematicSimulationTrajectoryExecutor.cpp
- src/planner/vectorfield/MoveEndEffectorOffsetVectorField.cpp
- src/robot/IkFast.cpp
- src/robot/Robot.cpp
- src/statespace/dart/MetaSkeletonStateSpace.cpp
- src/trajectory/util.cpp
Previously, the Robot class only worked with "controlled MetaSkeletons" by default (i.e. the MetaSkeleton stripped of all fixed and R0 joints). However, our planners do not make that distinction by default. Therefore, there were number-of-joint mismatches between many generated trajectories and their corresponding MetaSkeletons when checking state space compatibility.
The solution was to either:
(1) Update the codebase to strip all R0 joints from any MetaSkeletons we plan on.
OR
(2) Just remove the concept of joints entirely from the MetaSkeletonStateSpace and only deal with DoFs.
Because DART already deals only with DoFs in functions like "getPositions", this push goes for the latter.
As a consequence, some conversion code that claims to only work with R1 and SO2 joints was updated to …
> Check ability of Robot class to handle R0 joints

- src/robot/Robot.cpp
Quick 1-line fix to Robot class.
***
- [ N/A ] Set version target by selecting a milestone on the right side
- [ N/A ] Summarize this change in `CHANGELOG.md`
> Make sure self-collision chcks entire skeleton, not just subrobot

- CHANGELOG.md
- include/aikido/common/util.hpp
- include/aikido/planner/dart/ConfigurationToEndEffectorPosePlanner.hpp
- include/aikido/planner/vectorfield/MoveEndEffectorPoseVectorField.hpp
- include/aikido/planner/vectorfield/VectorFieldConfigurationToEndEffectorPosePlanner.hpp
- include/aikido/planner/vectorfield/VectorFieldPlanner.hpp
- include/aikido/robot/Robot.hpp
- include/aikido/robot/util.hpp
- src/planner/CMakeLists.txt
- src/planner/dart/ConfigurationToEndEffectorPosePlanner.cpp
- src/planner/vectorfield/CMakeLists.txt
- src/planner/vectorfield/MoveEndEffectorPoseVectorField.cpp
- src/planner/vectorfield/VectorFieldConfigurationToEndEffectorPosePlanner.cpp
- src/planner/vectorfield/VectorFieldPlanner.cpp
- src/robot/Robot.cpp
- tests/common/CMakeLists.txt
- tests/common/test_util.cpp
- tests/planner/vectorfield/test_VectorFieldPlanner.cpp
Instead of creating a whole new ConfigurationToEndEffectorTwist problem and planner (which would be somewhat redundant with ConfigurationToEndEffectorOffset), piggy-back on top of the ConfigurationToEndEffectorPose problem to create a planToPoseOffset function in the Robot class.
In effect, if you add a desired translation and rotation of the end-effector, this will attempt to follow a Vector Field defined by the Jacobian of the configuration space to achieve that translation and rotation. If rotation is 0, Twist and Offset should output identical results.
***
> Add planToPoseOffset via VectorFieldPosePlanner

- CHANGELOG.md
- include/aikido/common/util.hpp
- include/aikido/robot/util.hpp
- src/external/kunz_retimer/Trajectory.cpp
- src/robot/Robot.cpp
Previously, in the case of an empty trajectory (which is possible for an Offset planner with 0 offset or a configuration planner with goal == start), the resulting trajectory was length 0.
In this case, any postprocessor should return a valid (but empty) trajectory.
However, Kunz's Trajectory class initially timed the trajectory using the velocity without checking for 0 velocity. If there is 0 velocity but non-0 position, the trajectory is invalid (this should never happen). But if there is 0 velocity AND 0 change in position, the trajectory is valid but empty, and Kunz shouldn't perform the division (which results in a NaN endTime, which in turn leads to a *VERY LARGE* sequence of waypoints when naively constructed with aikido::common::StepSequence, which in turn causes the program to …
> Remove bug where Kunz hangs on empty trajectory
